### PR TITLE
Allow alligning of dots on x axis

### PR DESCRIPTION
**Pull request by dbarner1**
Proposes aligning the dots on the x axis if the user would like to.

### CODE REVIEW

**Comment by dbarner1** [comment]
Hi team (@yasaricli, @canyener, @ilhantekir, @hasankemaldemirci)

- Thank you for putting this together 🙏 
- This is a PR to allow users to have all dots align on the X axis if they wish.  Would you mind approving and pushing to npm?

Thank you,
Dave

**Comment by yasaricli** [comment]
hey @dbarner1, thank you very much for your contribution.

**Comment by yasaricli** [comment]
You can see it in version [0.1.7](https://github.com/tsepeti/react-native-dots-pagination/releases/tag/0.1.7). Thanks again.

**Comment by dbarner1** [comment]
Good doin' business, fellas!

**Pull request merged**
